on: push
jobs:
  load-Bot:
    title: Loading Bot
    runs-on: ubuntu-latest
    container: node:16.14.0
    steps:
     - run: node --version
     - run: npm --version
     - uses: actions/checkout@v3
     - run: npm install
  run-Bot:
    title: Running Bot
    runs-on: ubuntu-latest
    container: node:16.14.0
    steps:
     - run: node index.js
     