name: Load Bot
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:16.14.0
    steps:
     - name: Check Node Version
       run: node --version
     - name: Check NPM Version
       run: npm --version
     - uses: actions/checkout@v3
     - name: Install NPM
       run: npm install
     - name: Get Workflow IDS
       run: curl https://api.github.com/repos/elena-martin/qimo-bot/actions/workflows
     