name: Load & Run Bot
on: 
  workflow_dispatch:
jobs:
  load-Bot:
    runs-on: ubuntu-latest
    container: node:16.14.0
    steps:
     - name: Check Node Version
       run: node --version
     - name: Check NPM Version
       run: npm --version
     - uses: actions/checkout@v3
     - name: Install NPM
       run: npm install
     - name: Get Workflow IDs
       run: curl https://api.github.com/repos/elena-martin/qimo-bot/actions/workflows
     - name:Ge Token
       run: curl -u username:token https://api.github.com/user
  run-Bot:
    needs: load-Bot
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run Bot
       run: node index.js
     
