name: Pong
env:
  REPO_OWNER: elena-martin
  REPO_NAME: qimo-bot
  GITHUB_TOKEN: ${{ secrets.TOKEN}}
on:
  repository_dispatch:
    types: [run-pong]
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run Pong
        run: npm run pong