name: Pong
env:
  REPO_OWNER: elena-martin
  REPO_NAME: qimo-bot
on:
  repository_dispatch:
    types: [run-pong]
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pong
        run: npm run pong